version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3010:3010
    command: npm start
    networks:
      - backend
networks:
  backend:
    driver: bridge